export {
  IconArrowRight,
  IconArrowUpRight,
  IconBell,
  IconBrandInstagram,
  IconBrandX,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconHeart,
  IconHome,
  IconLogin2,
  IconMail,
  IconMapPin,
  IconMinus,
  IconNotebook,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhone,
  IconPlus,
  IconPrinter,
  IconRulerMeasure,
  IconSearch,
  IconShieldCheck,
  IconShoppingBag,
  IconShoppingCart,
  IconLayoutGrid,
  IconTrash,
  IconTruck,
  IconUser,
  IconX,
  type IconProps,
} from "@tabler/icons-react";
